spring:
  application:
    name: pms-user-service
  data:
    mongodb:
      uri: mongodb://mongo:mongo@127.0.0.1:27017/pms-user?authSource=admin

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/