version: '3.1'

services:

  mongo-booking:
    image: mongo
    restart: always
    container_name: mongo-booking
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: pms-booking
    ports:
      - 27019:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
#    container_name: elasticsearch
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    ports:
#      - 9200:9200
#      - 9300:9300

#docker-compose up --build -d mongo